#!/bin/bash
# Updated environment variables for Milvus Search Embeddings
export MY_DB_NAME="my_database"
export MILVUS_OLLAMA_COLLECTION_NAME="milvus_ollama_collection"
export MILVUS_HF_COLLECTION_NAME="milvus_hf_collection"
export EMBEDDING_PROVIDER="ollama"
export OLLAMA_LLM_MODEL="llama3.2"
export OLLAMA_EMBEDDING_MODEL="nomic-embed-text:v1.5"
export HF_EMBEDDING_MODEL="sentence-transformers/all-MiniLM-L6-v2"
export HF_LLM_MODEL="sentence-transformers/all-MiniLM-L6-v2"
export OLLAMA_NUM_THREADS="8"
export TOKENIZERS_PARALLELISM="false"
export PYTORCH_MPS_HIGH_WATERMARK_RATIO="0.0"
export USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
export MILVUS_HOST="localhost"
export MILVUS_PORT="19530"
# export HUGGINGFACEHUB_API_TOKEN="your_huggingface_token_here"

echo "Environment variables set successfully!"
echo "OLLAMA_LLM_MODEL: $OLLAMA_LLM_MODEL"
echo "OLLAMA_EMBEDDING_MODEL: $OLLAMA_EMBEDDING_MODEL"
echo "HF_EMBEDDING_MODEL $HF_EMBEDDING_MODEL"
echo "HF_LLM_MODEL: $HF_LLM_MODEL"